FROM cross-stretch AS builder

COPY ./hello.cpp /code/

ENV BIN_DIR /tmp/bin

RUN mkdir -p $BIN_DIR && \
  $CXX_COMPILER_ARM_LINUX /code/hello.cpp -Ofast -Wall -o $BIN_DIR/hello

FROM scratch
COPY --from=builder /tmp/bin /
